### PR TITLE
Allow commands that run through the current PATH, or with additional parameters

### PR DESCRIPTION
**Pull request by waneck**
See #33

### CODE REVIEW

**Comment by jcward** [comment]
@waneck sorry for being slow on this one -- I'm very busy at work and haven't had time to test the 6 launch conditions (3 OS's, terminal and not terminal.)

**Comment by waneck** [comment]
No problem. I'll see if I can help testing it. By looking at the code, it seems that at least with `terminal` off, it should work on all platforms - we already do that for the compilation call.
I'm not sure about terminal mode, though

**Comment by jcward** [comment]
Yeah, terminal mode is quite different on each platform.

Hmm, I'd be ok accepting this PR and filing an issue to check terminal mode. It's a non-breaking change that would still continue to work with any existing .json settings.

**Comment by waneck** [comment]
Thank you!

**Pull request merged**
